# Jacob L Stewart
# Chapter 6 Assignment 01
# A program that initializes a list with ten random integers and then prints four lines of output, containing:
# Every element at an even index.
# Every even element.
# All elements in reverse order.
# Only the first and last element.
import random


# @param randomInts is used to save the product of the 10 randomly generated integers.
def main():
    randomInts = getRandomInts()
    # checks for even index numbers in list
    evenInd = randomInts[1::2]
    print("10 random integers:", randomInts)
    # reversed function used to display list backwards.
    reverseList = list(reversed(randomInts))
    print("List in reverse order:", reverseList)
    # @evenInd, combs the list for [1::2] splicing
    print("Integers at even Index:", evenInd)
    # even numbers and first and last elements using functions below.
    print("Even numbers in list:", getEvenNumbers(randomInts))
    print("First and Last elements in list:", getFirstAndLast(randomInts))


# @param randomIntegerList holds the values generated by the randint() function
def getRandomInts():
    randomIntegerList = []
    # for loop that generates a random #1-30 until 10 numbers are stored
    for i in range(0, 10):
        rndInt = random.randint(1, 30)
        randomIntegerList.append(rndInt)
    return randomIntegerList


# @param evenNumbers, checks each number to see if divisible by 2 = 0 (even numbers only)
def getEvenNumbers(intlist):
    evenNumbers = [num for num in intlist if num % 2 == 0]
    return evenNumbers


# iterates over list given and returns 0 index (first) and -1 for last index (only usable in python)
def getFirstAndLast(intlist):
    firstAndLast = [intlist[i] for i in (0, -1)]
    return firstAndLast


main()
